const Bengali = {
    message: {
        header: {
            name: 'স্টুডেন্ট ট্র্যাকার সিস্টেম',
            Search: 'অনুসন্ধান',
            ChangeLanguage: 'ভাষা পরিবর্তন:',
            Placeholder: 'একটি রেজিস্ট্রেশন নম্বর লিখুন',
        },
        homeContent: {
            name: 'স্টুডেন্ট ট্র্যাকার সিস্টেম',
            showMessage: 'স্টুডেন্ট পরিচালনার জন্য সাইডবারে অপশনগুলো ক্লিক করুন।',
            schoolName: "কেন্দ্রীয় বিদ্যালয়",
        },
        AddNewStudent: {
            FirstName: 'প্রথম নাম',
            LastName: 'শেষ নাম',
            Standard: 'শ্রেণী',
            Address: 'ঠিকানা',
            Mobile: 'মোবাইল নম্বর',
            Email: 'ইমেইল আইডি:',
            Submit: 'জমা দিন',
            btnText4: 'স্নাতক',
            error_firstname_lastname_number: "্রথম নাম বা শেষ নাম সংখ্যা হতে পারে না",
            error_standard_range:"ছাত্র সফলভাবে যোগ করা হয়েছে!",
            success_student_added:"ছাত্র সফলভাবে যোগ করা হয়েছে!",
            error_student_add_failed:"ছাত্র যোগ করতে ব্যর্থ হয়েছে",
            GO_BACK: "িরে যান",
        },
        Promote: {
            promote: 'শিক্ষার্থী উন্নীত করুন',
            InputFieldText: 'একটি রেজিস্ট্রেশন নম্বর লিখুন',
            btnText: 'উন্নীত করুন',
            btnText2: 'টিসি',
            GenerateTransferCertificate: 'ট্রান্সফার সার্টিফিকেট তৈরি করুন',
            btntext3: 'বিস্তারিত দেখুন',
            success: "ছাত্র আইডি {id} সফলভাবে উন্নীত হয়েছে!",
            failed: "পদোন্নতি করতে ব্যর্থ!"
        },
        ShowAllStudents: {
            StudentInformation: "ছাত্রের তথ্য",
            RegistrationNo: 'রেজিস্ট্রেশন নম্বর',
            RollNo: 'রোল নম্বর',
            FirstName: 'প্রথম নাম',
            LastName: 'শেষ নাম',
            Standard: 'শ্রেণী',
            AdmissionDate: 'ভর্তির তারিখ',
            Address: 'ঠিকানা',
            Mobile: 'মোবাইল নম্বর',
            Email: 'ইমেইল আইডি:',
            Status: 'স্থিতি',
            PromoteStudent: 'শিক্ষার্থী উন্নীত করুন',
            TCGeneration: 'টিসি জেনারেশন',
            generate_tc_title: "ছাত্রের টিসি তৈরি করবেন?",
            confirm:"নিশ্চিত করুন",
            cancel:  "বাতিল করুন",
            graduate_student_title: "ছাত্রকে স্নাতক ঘোষণা করবেন?",
            promote_student_title: "ছাত্রকে পদোন্নতি দিতে চান?",
            success_tc_generated: "আইডি {regNo} এর জন্য ট্রান্সফার সার্টিফিকেট তৈরি হয়েছে",
            failed_to_graduate: "স্নাতক হতে ব্যর্থ হয়েছে!",
            tc_generated: "টিসি তৈরি হয়েছে",
            GO_BACK: "ফিরে যাও",
        },
        SideBar: {
            Home: 'হোম',
            AddStudent: 'শিক্ষার্থী যোগ করুন',
            PromoteStudent: 'শিক্ষার্থী উন্নীত করুন',
            ShowAllStudents: 'সব শিক্ষার্থী দেখান',
            PromoteNextStd: 'পরবর্তী শ্রেণিতে উন্নীত করুন',
            GenerateTC: 'টিসি তৈরি করুন',
        }
    }
}
export default Bengali;
